spring:
    config:
            import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        properties:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        generate-ddl: false
        show-sql: true
server:
    port: ${PORT:8080}