spring:
    config:
            import: optional:file:.env[.properties]
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
    jpa:
        properties:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        generate-ddl: false
        show-sql: true